/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnalyticsEventType } from './analyticsEventType';

export interface AnalyticsEvent {
  id?: string;
  type?: AnalyticsEventType;
  source?: string;
  projectId?: string;
  createdAt?: string;
}
