/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AnalyticsEventType = typeof AnalyticsEventType[keyof typeof AnalyticsEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsEventType = {
  profile_view: 'profile_view',
  project_view: 'project_view',
  contact_submit: 'contact_submit',
  cv_download: 'cv_download',
} as const;
