/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnalyticsMetric } from './analyticsMetric';

export interface AnalyticsOverviewCards {
  profileViews?: AnalyticsMetric;
  projectViews?: AnalyticsMetric;
  contactRequests?: AnalyticsMetric;
  cvDownloads?: AnalyticsMetric;
}
