/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnalyticsEventRequestType } from './analyticsEventRequestType';

export interface AnalyticsEventRequest {
  type?: AnalyticsEventRequestType;
  source?: string;
  projectId?: string;
}
