/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnalyticsOverviewCards } from './analyticsOverviewCards';

export interface AnalyticsOverviewResponse {
  from?: string;
  to?: string;
  cards?: AnalyticsOverviewCards;
}
