/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Contact {
  id?: string;
  fullName?: string;
  email?: string;
  howCanIHelp?: string;
  createdAt?: string;
  lastUpdated?: string;
}
