/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FindByLocationParams = {
/**
 * Location to search
 */
location: string;
};
