/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Project {
  id?: string;
  name?: string;
  description?: string;
  url?: string;
  technologies?: string[];
  lastUpdated?: string;
  isVisible?: boolean;
}
