/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Skill {
  id?: string;
  name?: string;
  logoUrl?: string;
  lastUpdated?: string;
  isVisible?: boolean;
}
