/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Project } from './project';
import type { Skill } from './skill';
import type { Experience } from './experience';

export interface User {
  id?: string;
  name?: string;
  email?: string;
  password?: string;
  roles?: string[];
  about?: string;
  profileImage?: string;
  projects?: Project[];
  skills?: Skill[];
  experiences?: Experience[];
}
